// eslint-disable-next-line no-unused-expressions
export const booksMocks = [
  {
    id: "64c1ec20df73bab6e8e6f056",
    title: "The Adventures of Sherlock Holmes",
    description:
      "A collection of detective stories by Arthur Conan Doyle. I m shiv",
    price: "32.9",
    author: "Arthur Conan Doyle",
    publisher: "George Newnes",
  },
  {
    id: "64c1ec40df73bab6e8e6f056",
    title: "The Picture of Dorian Gray",
    description: "A novel by Oscar Wilde.",
    price: 10.49,
    author: "Oscar Wilde",
    publisher: "Lippincott's Monthly Magazine",
  },
  {
    id: "64c1ec00d373bab6e8e6f056",
    title: "One Hundred Years of Solitude",
    description: "A novel by Gabriel García Márquez.",
    price: 15.99,
    author: "Gabriel García Márquez",
    publisher: "Editorial Sudamericana",
  },
  {
    id: "24c1ec00df73bab6e8e6f056",
    title: "The Catcher in the Rye",
    description: "A novel by J.D. Salinger.",
    price: 11.99,
    author: "J.D. Salinger",
    publisher: "Little, Brown and Company",
  },
  {
    id: "64c20ce9df73bab6e8e6f06c",
    title: "The Lord of the Rings",
    description: "A high-fantasy epic novel by J.R.R. Tolkien.",
    price: 24.99,
    author: "J.R.R. Tolkien",
    publisher: "George Allen & Unwin",
  },
  {
    id: "64c20d2adf73bab6e8e6f06d",
    title: "Jane Eyre",
    description: "A novel by Charlotte Brontë.",
    price: 13.99,
    author: "Charlotte Brontë",
    publisher: "Smith, Elder & Co.",
  },
  {
    id: "55c20d5fdf73bab6e8e6f06e",
    title: "The Great Expectations",
    description: "A novel by Charles Dickens.",
    price: 12.49,
    author: "Charles Dickens",
    publisher: "Chapman & Hall",
  },
  {
    id: "64c20eb0df73bab623e6f073",
    title: "The Alchemist",
    description: "A novel by Paulo Coelho.",
    price: 10.99,
    author: "Paulo Coelho",
    publisher: "HarperOne",
  },
  {
    id: "64c20f8adf73bab538e6f076",
    title: "Brave New World",
    description: "A dystopian novel by Aldous Huxley.",
    price: 9.99,
    author: "Aldous Huxley",
    publisher: "Chatto & Windus",
  },
  {
    id: "64c1ec00df56bab6e8e6f056",
    title: "Moby-Dick",
    description: "A novel by Herman Melville.",
    price: 13.99,
    author: "Herman Melville",
    publisher: "Harper & Brothers",
  },
  {
    id: "54320d5fdf73bab6e8e6f06e",
    title: "The Adventures of Huckleberry Finn",
    description: "A novel by Mark Twain.",
    price: 12.49,
    author: "Mark Twain",
    publisher: "Chatto & Windus",
  },
  {
    id: "64c5ec00df73bab2e8e6f256",
    title: "One Hundred Years of Solitude",
    description: "A novel by Gabriel García Márquez.",
    price: 15.99,
    author: "Gabriel García Márquez",
    publisher: "Editorial Sudamericana",
  },
  {
    id: "64c14200df73bab6e8e6f156",
    title: "Jane Eyre",
    description: "A novel by Charlotte Brontë..",
    price: 9.99,
    author: "Charlotte Brontë",
    publisher: "J. B. Lippincott & Co.",
  },
  {
    id: "64c5ec00d233bab2e8e6f256",
    title: "the Great Expectations",
    description: "A novel by Charles Dickens.",
    price: 15.99,
    author: "Charles Dickens",
    publisher: "Chapman & Hall",
  },
  {
    id: "64c5ec00d233b2b2e8e6f256",
    title: "The Adventures of Huckleberry Finns",
    description: "A novel by Mark Twain.",
    price: 15.99,
    author: "Twain",
    publisher: "Twain Mark",
  },
  {
    id: "64c1ec00df73bab2e0e6f056",
    title: "The Picture of Dorian Gray",
    description: "A classic novel by Dorian Gray.",
    price: 12.99,
    author: "Aviral",
    publisher: "Aviral Scribner's Sons",
  },
  {
    id: "94c5ec00d233b2b2e8e6f256",
    title: "Titatic ",
    description: "A novel about titatic.",
    price: 15.99,
    author: "Malo kahn",
    publisher: "Mark",
  },
  {
    id: "04d1ec11df73bab6e8e6f156",
    title: "Titanic",
    description: " Edward Lee.",
    price: 9.99,
    author: "Edward Lee",
    publisher: "Lippincott & Co.",
  },
  {
    id: "64c1ec00df73ba26e846f056",
    title: "Inception",
    description: "A Christopher Nolan book.",
    price: 12.99,
    author: "Christopher",
    publisher: "Christopher's Sons",
  },
  {
    id: "94d5e000d233b2b2e8e6f256",
    title: "12 Angry Men ",
    description: "A novel about Judges.",
    price: 15.99,
    author: "Salar zafar",
    publisher: "Preston",
  },
  {
    id: "64c21825df73bab6e3e6f09d",
    title: "Go Tommy Go of Solitude",
    description: "A novel by Márquez.",
    price: 15.99,
    author: "Gabriel Márquez",
    publisher: "Editorial Sudamericana",
  },
  {
    id: "64c21857df73ba06e8e6f09e",
    title: "Goodwill hunting",
    description: "A novel by romance and comedy.",
    price: 15.99,
    author: "eric",
    publisher: "Sudamericana",
  },
  {
    id: "64c21884df734ab6e8e6f09f",
    title: "The Adventures of Sherlock Holmes",
    description: "chen Lee.",
    price: 9.99,
    author: "chen Lee",
    publisher: "luo & Co.",
  },
  {
    id: "94c218c4df73bab6e8e6f0a0",
    title: "Crime and Punishment",
    description: "Fyodor.",
    price: 9.99,
    author: "Fyodor Fyodor Lee",
    publisher: "Cambridge & Co.",
  },
  {
    id: "64c21910df73bab6e8e6f0a2",
    title: "1984",
    description: "A dystopian novel by George Orwell Lee.",
    price: 9.99,
    author: "George Orwel",
    publisher: "Texas & Co.",
  },
  {
    id: "64c21953df73bab6e0e6f0a4",
    title: "Hobbit",
    description: "Odor.",
    price: 9.99,
    author: "Texas Tech",
    publisher: "Texas Tech & Co.",
  },
  {
    id: "64c2199cdf73bab6e8e6f0a5",
    title: "Harry Porter",
    description: "Christopher Nolan.",
    price: 9.99,
    author: "Nolan Publishers",
    publisher: "Pushliser United.",
  },
  {
    id: "64c219d1df73bab6e8e6f0a6",
    title: "Apple",
    description: " Apple documentry.",
    price: 9.99,
    author: "Steve Job",
    publisher: "Apple Inc",
  },
  {
    id: "64c4445faee41259c8a07868",
    title: "aviral",
    description: "avira's book",
    price: 12.3,
    author: "aviral",
    publisher: "aviral",
  },
  {
    id: "64c487e508b515440f0a3c04",
    title: "Advance DB",
    description: "Book about DB",
    price: 20,
    author: "Salar",
    publisher: "Texas Tech",
  },
];
